name: Releases

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo "ART_TAG=v$(cat version.txt)" >> $GITHUB_ENV
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.ART_TAG }}
        skipIfReleaseExists: true
        makeLatest: true
        draft: true
        body: "This is a test release"
